version: "3"
services:
    feb-accounts:
        image: ahmdrifai/feb-accounts:prod
        container_name: feb-accounts
        restart: unless-stopped
        tty: true
        env_file: .env
        networks:
            - feb-accounts-prod

    feb-accounts-webserver:
        image: ahmdrifai/feb-accounts-webserver:prod
        container_name: feb-accounts-webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8002:80"
        depends_on:
            - feb-accounts
        networks:
            - feb-accounts-prod

#Docker Networks
networks:
    feb-accounts-prod:
        driver: bridge
